### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by mastahcez** [KN4CK3R/KeePassQuickUnlock#1]
Doesn't work on Lubuntu 16.04. 

Keepass v. 2.33 - current version on jtalylor ppa.

"Incompatible with current Keepass version"

**Comment by KN4CK3R** [comment]
I don't have tested it with Mono but with Windows you need to have .Net 4 installed. Don't know which Mono version you need to use, sry.

**Comment by KN4CK3R** [comment]
Now I have tested KeePass with Ubuntu 16.04 and I can't use KeePass with a single extension. Every extension gives me an error, so this isn't an error of my plugin.

**Comment by siamak2** [comment]
I have tested KeePassQuickUnlock 2.0.0.0 on Ubuntu 16.04 with latest version of mono-complete and keepass 2.32.
The plugin works fine.
I haven't tested KeePassQuickUnlock 2.1.

**Comment by KN4CK3R** [comment]
Good to know, thank you!

**Comment by paddylandau** [comment]
I was also getting this with all plugins (except [Ubuntu Integration Plugins](http://keepass.info/plugins.html#linuxint)) on Ubuntu 16.04 (64-bit).

I figured out how to fix this, thanks to the comment by @siamak2. All that I needed to do was to install mono-complete (it's in the repository). I would not have known to do this!
