### ISSUE TITLE
QuickUnlock only works once

### ISSUE THREAD

**Issue by Neclony** [KN4CK3R/KeePassQuickUnlock#10]
I really love this plugin but sadly it doesn't work properly on my pc.

After using QuickUnlock once the next time I want to unlock my database it won't let me use QuickUnlock and the little window from KeePass2 forgets my keyfile. I have to reselect the keyfile manually and use my masterpasswort! Then it works only once again.

I tried different periodes than "Unlimited" in the options but it's always the same.

Do you have any advice for me?

**Comment by KN4CK3R** [comment]
Read the readme chapter "HOW TO USE"

**Comment by Neclony** [comment]
Okay thanks, clearly my fault! ^^
Too bad that the "Part of" only works once...

There is still one problem:
First login of the day(startup) or when the QuickUnlock key is expired I have to reselect my keyfile(It's not in the dropdown I need to search it with the file explorer!)

Is this intended?

**Comment by KN4CK3R** [comment]
No, but isn't it the default if you restart KeePass? Does KeePass remember the last key file location? I thought that only works because KeePass remembers the path in memory (and no other key provider was used).
I don't know if I can force KeePass to use the last known key file. These parts are not visible to plugin developers and I don't know if I should make changes to KeePass internals because they could change with every version.

**Comment by Neclony** [comment]
Just tried it without plugins, KeyPass2 remembers keyfile location at startup.
With QuickUnlock enabled it forgets the keyfile on first login if I used Quickunlock once or more often in the last session. Double-checked!

I coudn't reproduce it with the expired key though.

**Comment by KN4CK3R** [comment]
Ok, I will see if I can resolve that.

**Comment by KN4CK3R** [comment]
I have looked into the code and sadly I can't force KeePass to remember the key file path after you have used QuickUnlock. KeePass tests if your masterkey contains a keyfile but after unlocking with QuickUnlock, the masterkey only contains the QuickUnlock key so no path is saved.
This would only work if key provider plugins are able to return more than one key.

**Comment by QuentinC** [comment]
Hello,

I'm using your plugin everyday, and it works great !
I would just like to know if this issue is still in investigation (maybe in relation with Keepass Dev Team ?) or if it won't be fixed ?

Thanks !

Quentin

**Comment by KN4CK3R** [comment]
Currently it won't be fixed because the KeePass API is designed as it is.
