### ISSUE TITLE
Path to keyfile is no longer available

### ISSUE THREAD

**Issue by saxofooon** [KN4CK3R/KeePassQuickUnlock#13]
If you unlock keepass, the path to the keyfile is no longer rememberd by keepass. In the dropdown field for the path is only Quickunlock selectable, so you have to search manually for the keyfile every time. Any ideas?
These options are active:
Remember key sources
Automatically search key files

**Comment by KN4CK3R** [comment]
See here:
https://github.com/KN4CK3R/KeePassQuickUnlock/issues/10#issuecomment-247460958
and here:
https://github.com/KN4CK3R/KeePassQuickUnlock/issues/7#issuecomment-232715543
