### ISSUE TITLE
QuickUnlock 2.2.0.0 and KeePass 2.35 not working

### ISSUE THREAD

**Issue by mcassaniti** [KN4CK3R/KeePassQuickUnlock#15]
I assume this is a user error problem, but I've done the following on Windows:
- Installed KeePass 2.35
- Added KeePassQuick Unlock plugin version 2.2.0.0
- Added an entry with a title called QuickUnlock (no spaces) that has the same password as my DB
- Set the following Quick Unlock options:
  - Quick Unlock Entry only
  - Auto prompt for the Quick Unlock key if it is available
  - Invalidate after 1 day (tried with unlimited as well)
  - Origin: Front
  - Length: 4

I locked the database and unlocked it. The Quick Unlock prompt came up and I can see behind it that the normal KeePass prompt shows the master password box not selected, and the key file box is selected with "Quick Unlock" as the key file. I typed the first 4 characters of my DB password in, and I get a response of "the composite key is invalid".

Please note that I don't use a key file normally, just a password. I'm very grateful for the effort you've put in and I'm looking forward to having this working similar to how Keepass2Android works.

**Comment by KN4CK3R** [comment]
Yep, thats an user error. ;)
You selected "Quick Unlock Entry only" but want to use "Part of Master Password". If you select "Quick Unlock Entry only" you will have to enter the password this entry has (doesn't make sense to use your master password here). You need the "Part of Master Password" mode if you want to unlock the database with the first 4 characters of your master password. But have in mind the gray box here: https://github.com/KN4CK3R/KeePassQuickUnlock#how-to-use As a workaround you can create the QuickUnlock entry with your first 4 characters as password. This will work too.

**Comment by mcassaniti** [comment]
JFTR I set the option 'Part of Master Password' and also needed to make sure I removed my Quick Unlock entry from the DB.

**Comment by KN4CK3R** [comment]
Yes, forgot to tell you this. The QuickUnlock entry is always preferred because it will work all the time.
