### ISSUE TITLE
[enhancement] QuickUnlock wider time range invalidation

### ISSUE THREAD

**Issue by WindRider7** [KN4CK3R/KeePassQuickUnlock#17]
Hello, Is it possible to select a wider timer range after which QuickUnlock should be invalidated ?
I would like to set 3 days invalidation time, or 1 week perhaps.

**Comment by WindRider7** [comment]
Ok. I tried to use this plugin and figured out that you have to unlock your database with the full password every time you want to use quick unlock, that makes more sense now. I would prefer having quick unlock with the possibility to close the database fully, but I don't know if it possible to implement technically.

**Comment by KN4CK3R** [comment]
Sure but you would need to store it in a file not just in memory. So you could save the weaker key along with your database in a dropbox and an attacker would only need to attack the weaker key to get access to your main database. I don't think that is what you want.
