### ISSUE TITLE
KeePass no longer remembers database unlock configuration after restart KeePass

### ISSUE THREAD

**Issue by dbw9580** [KN4CK3R/KeePassQuickUnlock#18]
With QuickUnlock enabled, when I close an open database and open it again , QuickUnlock gets prompted and ask me for the quick pass. But if I close KeePass itself and start it again, open a database, KeePass doesn't remember what configuration was set to unlock the database (e.g. password and a key file, as well as the path to that key file). Normally KeePass remembers my database uses a key file and fills in the block with the path to it so I don't have to mannually select it from a dialogue box.

I have "remember and automatically open last used database at startup" and "remember key sources" enabled in the keepass settings.

Steps to reproduce:
1. Start KeePass and open a database file for the first time. Manually input the password and select a key file. Database gets unlocked and opened.
2. Lock and unlock the workspace for at least once during use, or close and reopen the database. This time QuickUnlock is activated and I can unlock it with a quick password.
3. Exit KeePass and restart it. When opening the same database, KeePass no longer remembers the unlock configuration.

![default](https://cloud.githubusercontent.com/assets/6999708/26109507/52a9c26e-3a82-11e7-976b-1c54ff6da7ef.png)

**Comment by KN4CK3R** [comment]
See here:
https://github.com/KN4CK3R/KeePassQuickUnlock/issues/10#issuecomment-247460958
and here:
https://github.com/KN4CK3R/KeePassQuickUnlock/issues/7#issuecomment-232715543
