### ISSUE TITLE
QuickUnlock is not available for this database.

### ISSUE THREAD

**Issue by mastahcez** [KN4CK3R/KeePassQuickUnlock#2]
Windows 8 64bit, Keepass 2.34. This is an existing database that was created in linux but works fine in windows.

**Comment by KN4CK3R** [comment]
Do you need a keyfile or your windows account to unlock the database? Quick Unlock supports only simple password protected databases.

**Comment by mastahcez** [comment]
Yes it needs a keyfile, I didn't know that it's not supported, thanks.
Are there any plans to make it work with a keyfile?

**Comment by KN4CK3R** [comment]
The QuickUnlock plugin works like a key file provider for KeePass so you can't have both currently. I will see if I can add it but I think for this KeePass must support something like QuickUnlock out of the box.

**Comment by mastahcez** [comment]
I see, well it would be great, I'm too paranoid to abandon keyfiles.
Cheers

**Comment by forkery** [comment]
same problem here need a fix for keyfiles

**Comment by KN4CK3R** [comment]
Keyfile support was added in v2.0

**Comment by forkery** [comment]
I mean support for CertKeyProviderPlugin by Mark Buchler. It would be great if you''ll add an option to auto open the databases protected with CertKeyProviderPlugin not just the regular keyfile. Ether way you are doing a great job with this plugin! Keep up with that! :)

**Comment by KN4CK3R** [comment]
If you have unlocked the database with the cert the quickunlock with a passphrase doesn't work?

**Comment by mastahcez** [comment]
Thank you, works fine now! Would it be much to ask to make it remember the previous keyfile location and return to it in the open database dialog after the quicklock password is invalidated? It's just a minor inconvenience but right now it clears the dropdown and I have to search for my keyfile (I have it set to remember because I keep it on a usb stick anyway).
Thanks

**Comment by KN4CK3R** [comment]
Currently this is not possible, I don't have this information. :( See my answer here: https://github.com/KN4CK3R/KeePassQuickUnlock/issues/7#issuecomment-232715543

**Comment by ajg372** [comment]
When opening get the message .
Thanks for your help, greetings .
![error](https://cloud.githubusercontent.com/assets/8018877/17077752/5996221a-50dc-11e6-96f8-979865b3c5e5.gif)

**Comment by KN4CK3R** [comment]
Do you use the portable version?

**Comment by ajg372** [comment]
Yes, 
this portable version .

**Comment by KN4CK3R** [comment]
Ok, just tested it with the portable version 2.34, put the plgx into the plugins directory and it worked fine. You could start KeePass with the commandline parameter --debug. This will save the error to a file. You could upload it here (and create a new issue then please).

**Comment by ajg372** [comment]
KeePass --debug does not work , there is no file information
![keepass_error](https://cloud.githubusercontent.com/assets/8018877/17099341/13168338-5268-11e6-9d41-a128b30f7bfc.jpg)

**Comment by Meister1977** [comment]
Same problem here. As I see, Keypass itself has been built by .net 2.0. Your plugin built with .net 4.0. Can this the root of the problem?

[Window Title]
KeePass

[Content]
A következő bővítmények nem kompatibilisek a jelenlegi KeePass verzióval:
i:\munka\_Pass\KeePassQuickUnlock.plgx

Keressen a bővítmények honlapon egy megfelelő verziót.

[Expanded Information]
A(z) A következő típus nem található: System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. Sor: 123, pozíció: 5. ResX-fájl nem elemezhető.
System.Windows.Forms
   a következő helyen: System.Resources.ResXResourceReader.ParseXml(XmlTextReader reader)
   a következő helyen: System.Resources.ResXResourceReader.EnsureResData()
   a következő helyen: System.Resources.ResXResourceReader.GetEnumerator()
   a következő helyen: KeePass.Plugins.PlgxPlugin.CompileEmbeddedRes(PlgxPluginInfo plgx)
   a következő helyen: KeePass.Plugins.PlgxPlugin.Compile(String strTmpRoot, PlgxPluginInfo plgx, String strBuildPre, String strBuildPost)
   a következő helyen: KeePass.Plugins.PlgxPlugin.ReadFile(BinaryReader br, PlgxPluginInfo plgx, IStatusLogger slStatus)
   a következő helyen: KeePass.Plugins.PlgxPlugin.LoadPriv(String strFilePath, IStatusLogger slStatus, Boolean bAllowCached, Boolean bAllowCompile, Boolean bAllowLoad, TextWriter twLog)
   a következő helyen: KeePass.Plugins.PlgxPlugin.Load(String strFilePath, IStatusLogger slStatus)
Void ParseXml(System.Xml.XmlTextReader)


Inner:
A következő típus nem található: System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. Sor: 123, pozíció: 5.

[^] Részletek  [OK]

**Comment by Meister1977** [comment]
Ok, seems to me, if I copy the all folder from the portable zipo folder, not just the keepass.exe then it works.
