### ISSUE TITLE
Part of Master doesnt work with KeyPass 2.36

### ISSUE THREAD

**Issue by ladiko** [KN4CK3R/KeePassQuickUnlock#20]
I set the following options, but can't use the first 4 letters of my master password. If i add  the entry QuickUnlock and set it to the first 4 letters of my master password, it works as expected.

![image](https://user-images.githubusercontent.com/1856019/28068013-02285984-6644-11e7-8e69-9167472c9797.png)

Nice addon so far :)

**Comment by KN4CK3R** [comment]
Are you sure it just doesn't work after the first quick unlock? The "Part of Master" mode only works one time.

**Comment by ladiko** [comment]
Define "first quick unlock". It doesnt work on first or second try.

**Comment by KN4CK3R** [comment]
Works as expected for me.
1. Created a database with the master key "hellohello".
2. Set the settings as in your screenshot
3. Closed the database in KeyPass and reopened it from the filemenu.
4. QuickUnlock promts for the key
5. Provided "hell" and the database gets unlocked (<<< "first quick unlock")
6. repeated step 3
7. No QuickUnlock window pops up as expected and I need to type "hellohello" again. (<<< "second quick unlock")

**Comment by ladiko** [comment]
Neither by closing (Ctrl + W) and opening (Ctrl + O) or Locking and Unlocking by Ctrl + L works for me the way you describe. My password has 20 characters with several special, upper and lower characters and digits - but I guess that wont matter. Anyway, as I don't even want to unlock the second, fourth, sixth time etc. - I just stick with the QuickUnlock entry, which works fine for me.

Thanks for your time. :)

**Comment by thomas-zmo08179** [comment]
I've used the same settings: Quick entry / Part Of mode
PartOf mode doesn't work for me. Only the custom entry mode works. 

KeePass Version: 2.41

1. Created a database with the master key "hellohello".
2. Set the settings as in your screenshot
3. Closed the database in KeyPass and reopened it from the filemenu.
4. QuickUnlock promts for the key
5. Provided "hell" and the database **doesn't** gets unlocked (<<< "first quick unlock")
