### ISSUE TITLE
QuickUnlock Doesn't Work With Restart

### ISSUE THREAD

**Issue by stevenskov** [KN4CK3R/KeePassQuickUnlock#21]
I'm using it with its own key not the partof, and with unlimited setting. When I lock it, I can quick unlock it. But when I close KeePass2 and open it again, I can't quick unlock it. Is this how it's supposed to work or am I doing something wrong? Thank you

**Comment by KN4CK3R** [comment]
That's supposed. QuickUnlock only works if KeePass is running. It stores the database key encrypted in KeePass' memory (on Windows: in a safe memory region). If you close KeePass the memory gets erased and quick unlock isn't available anymore.
