### ISSUE TITLE
Exporting to KDB (1.x) doesn't work after database has been unlocked

### ISSUE THREAD

**Issue by kibinimatik** [KN4CK3R/KeePassQuickUnlock#22]

**Comment by KN4CK3R** [comment]
That's right. But it's not really a bug, just the way how KeePass works. You can't export to KDB files if you use something different from a password and/or a keyfile. You can't use a custom key provider (OTP, key cards, ...) with a KDB file.

See KdbFile.SetDatabaseKey for more informations.
