### ISSUE TITLE
version 2.3.0 still show as 2.2.0 in keepass

### ISSUE THREAD

**Issue by fbourqui** [KN4CK3R/KeePassQuickUnlock#24]

**Comment by fbourqui** [comment]
in the 2.3.0 plgx file available for download:
https://github.com/KN4CK3R/KeePassQuickUnlock/releases/download/v2.3/KeePassQuickUnlock.plgx

**Comment by KN4CK3R** [comment]
Thank you for the report. I fixed the download, just redownload it again.
