### ISSUE TITLE
Quick unlock doesn't work after restarting KeePass

### ISSUE THREAD

**Issue by iliyang** [KN4CK3R/KeePassQuickUnlock#4]
I've been looking for an ability to quickly unlock my KeePass database ever since I discovered PIN unlock in Windows 8 a while ago (running Windows 10 now). QuickUnlock looks very useful, but there's one issue that makes it actually less convenient for me than typing my full password the traditional way.

The thing is that if restart the KeePass application (or just run it for the first time after a reboot), QuickUnlock says "QuickUnlock is not available for this database". After I open the database once by entering the full password, subsequent unlocks work with QuickUnlock. I can even close the database and reopen it again, and QuickUnlock still works. It only fails when KeePass itself is restarted. And this is very inconvenient, because I have to click at the UI with the mouse to switch between QuickUnlock and full password. This defeats the purpose of the plugin, unfortunately :(

**Comment by KN4CK3R** [comment]
If you haven't entered your password the plugin can't know it so you must unlock your database first. If KeePass is closed every memory gets deleted so you need to input your full password again. That is not an issue, thats by design.

**Comment by iliyang** [comment]
Thanks for the quick response! Yes, I figured there might be a design issue there. I have no problem entering the full password the first time. The problem is that after that I have to manually switch to QuickUnlock by ticking checkboxes and choosing from a dropdown menu. Since I always launch KeePass, when it opens my hands are on the keyboard. So I find it easier to just enter the full password rather than tinkering with the UI. Do you think there's a way to automatically switch to QuickUnlock in the unlock dialog once the database has been unlocked once?

**Comment by KN4CK3R** [comment]
I think it should be possible to auto select QuickUnlock if the password form is shown for a known database. I will try it for the next version.

**Comment by iliyang** [comment]
That would be absolutely great, thank you!

**Comment by KN4CK3R** [comment]
QuickUnlock now is auto selected if a key is present.
