### ISSUE TITLE
unencrypted  password

### ISSUE THREAD

**Issue by forkery** [KN4CK3R/KeePassQuickUnlock#6]
how do you store the password? is there some sort of encryption, or is it stored in a plain text file?

**Comment by KN4CK3R** [comment]
The password doesn't get stored outside of KeePass! The plugin just holds a database <-> password association in memory. The password in this case is from KeePass which is only stored in encrypted form in memory.

**Comment by KN4CK3R** [comment]
For v2.0 this stays true. The password to quick unlock the database is stored in a custom database entry.

**Comment by rwese** [comment]
I'm sorry to dig this up, but didn't want to open another issue.

Would you mind add a quick expalantion how the quickunlock-password is stored?

**Comment by KN4CK3R** [comment]
Pin and "compiled" master password (combined key from password, keyfile, ...) are stored as ProtectedString / ProtectedBinary (Source: KeePassLib\Security\ProtectedBinary.cs). The ProtectedBinary class uses the DPAPI on Windows systems or ChaCha20 encryption on Mono (https://keepass.info/help/base/security.html , chapter Process Memory Protection). KeePass uses these classes to store the passwords while the database is unlocked. The values are only present in memory in unencrypted form while using them (showing a password in a dialog or in this case: comparing the pin and using the key to decrypt the database). If you use a public computer you should not use the plugin. But I don't know if you should KeePass at all on such a device.

**Comment by KN4CK3R** [comment]
Addition: See release notes for v2.3 (https://github.com/KN4CK3R/KeePassQuickUnlock/releases/tag/v2.3)

**Comment by rwese** [comment]
Thank your for the explanation and update!
