### ISSUE TITLE
QuickUnlock not working when time set to Unlimited

### ISSUE THREAD

**Issue by WolfspiritM** [KN4CK3R/KeePassQuickUnlock#8]
Hi,

Thank you for this plugin!
I tried setting the QuickUnlock time to "Unlimited" so I can always log in with the quick unlock password after one successful authentication, but with the time set to "Unlimited" and then locking or closing the Database and reopening it, it won't allow QuickUnlock to Unlock the database anymore. It always wants full Password + (in my case Yubikey) authentication.

Setting the Time back to "1 Day" works without issues again.

**Comment by KN4CK3R** [comment]
Thanks for the report, I forgot to handle the unlimited case. Will be fixed in the next version.

**Comment by KN4CK3R** [comment]
fixed in v2.1
https://github.com/KN4CK3R/KeePassQuickUnlock/releases/tag/v2.1
